site_name: napari-just-testing
site_description: Just testing napari cookiecutter
site_author: Talley Lambert

theme: readthedocs

repo_url: https://github.com/tlambert03/napari-just-testing

pages:
- Home: index.md
